FullData = {
    'Majors': {
        'accounting': '/UGRD/colleges-schools/UGACT/ACT_BSAC/',
        'advertising': '/UGRD/colleges-schools/UGJRC/ADV_BSAD/',
        'aerospace engineering': '/UGRD/colleges-schools/UGENG/ARO_BSAE/',
        'african languages': '/UGRD/colleges-schools/UGLAS/FAF_BA/',
        'african-american studies': '/UGRD/colleges-schools/UGLAS/AFA_BA/',
        'agricultural education and communication': '/UGRD/colleges-schools/UGAGL/AEC_BS/',
        'agricultural operations management': '/UGRD/colleges-schools/UGAGL/AOM_BS/',
        'animal sciences': '/UGRD/colleges-schools/UGAGL/ANS_BS/',
        'anthropology': '/UGRD/colleges-schools/UGLAS/APY_BA_BS/',
        'applied physiology and kinesiology': '/UGRD/colleges-schools/UGHHU/APK_BSAP/',
        'arabic': '/UGRD/colleges-schools/UGLAS/FAR_BA/',
        'architecture': '/UGRD/colleges-schools/UGDCP/ARC_BDES/',
        'art history': '/UGRD/colleges-schools/UGART/ARH_BAHA/',
        'art | ba': '/UGRD/colleges-schools/UGART/VAS_BA/',
        'art | bfa': '/UGRD/colleges-schools/UGART/ART_BFA/',
        'astronomy and astrophysics': '/UGRD/colleges-schools/UGLAS/ATY_BA_ASP_BS/',
        'biological engineering': '/UGRD/colleges-schools/UGENG/BE_BSBE/',
        'biology | cals': '/UGRD/colleges-schools/UGAGL/BLY_BS/',
        'biology | clas': '/UGRD/colleges-schools/UGLAS/BIO_BA_BS/',
        'biomedical engineering': '/UGRD/colleges-schools/UGENG/BME_BSBM/',
        'botany | cals': '/UGRD/colleges-schools/UGAGL/BTY_BS/',
        'botany | clas': '/UGRD/colleges-schools/UGLAS/BOT_BS/',
        'business administration | general studies | baba': '/UGRD/colleges-schools/UGBUS/BAG_BABA/',
        'chemical engineering': '/UGRD/colleges-schools/UGENG/CHE_BSCH/',
        'chemistry | biochemistry': '/UGRD/colleges-schools/UGLAS/CHY_BS/',
        'chinese': '/UGRD/colleges-schools/UGLAS/FCH_BA/',
        'civil engineering': '/UGRD/colleges-schools/UGENG/CVE_BSCE/',
        'classical studies': '/UGRD/colleges-schools/UGLAS/CLC_BA/',
        'communication sciences and disorders': '/UGRD/colleges-schools/UGPBH/CSD_BHS/',
        'computer engineering': '/UGRD/colleges-schools/UGENG/CPE_BSCO/',
        'computer science | clas': '/UGRD/colleges-schools/UGLAS/CSC_BS/',
        'computer science | herbert wertheim college of engineering': '/UGRD/colleges-schools/UGENG/CPS_BSCS/',
        'construction management': '/UGRD/colleges-schools/UGCMN/CM_BSCM/',
        'criminology': '/UGRD/colleges-schools/UGLAS/CRI_BA/',
        'dance | bachelor of arts': '/UGRD/colleges-schools/UGART/DAN_BA/',
        'dance | bachelor of fine arts': '/UGRD/colleges-schools/UGART/DAN_BFA/',
        'data science': '/UGRD/colleges-schools/UGLAS/DAT_BS/',
        'dietetics': '/UGRD/colleges-schools/UGAGL/DTS_BS/',
        'digital arts and sciences | bachelor of arts': '/UGRD/colleges-schools/UGART/DAR_BADA/',
        'digital arts and sciences | bachelor of science': '/UGRD/colleges-schools/UGENG/DAS_BSDA/',
        'dual languages': '/UGRD/colleges-schools/UGLAS/FLL_BA/FDU_BA/',
        'economics': '/UGRD/colleges-schools/UGLAS/ECO_BA/',
        'education sciences': '/UGRD/colleges-schools/UGEDU/EDS_BA/',
        'education | early childhood education | age 3-grade 3': '/UGRD/colleges-schools/UGEDU/EYC_BAE/',
        'electrical engineering': '/UGRD/colleges-schools/UGENG/ELE_BSEE/',
        'elementary education | grades k-6': '/UGRD/colleges-schools/UGEDU/EED_BAE/',
        'engineering | exploring engineering studies': '/UGRD/colleges-schools/UGENG/UES_NOD/',
        'english': '/UGRD/colleges-schools/UGLAS/EH_BA/',
        'entomology and nematology': '/UGRD/colleges-schools/UGAGL/ENY_BS/',
        'environmental engineering': '/UGRD/colleges-schools/UGENG/EVE_BSEN/',
        'environmental management in agriculture and natural resources | interdisciplinary studies': '/UGRD/colleges-schools/UGAGL/IS_BS01/',
        'environmental science': '/UGRD/colleges-schools/UGNTR/EVS_BA_BS/',
        'family, youth and community sciences': '/UGRD/colleges-schools/UGAGL/FYC_BS/',
        'finance': '/UGRD/colleges-schools/UGBUS/FIN_BSBA/',
        'food and resource economics': '/UGRD/colleges-schools/UGAGL/FRE_BS/',
        'food science': '/UGRD/colleges-schools/UGAGL/FOS_BS/',
        'foreign languages and literatures': '/UGRD/colleges-schools/UGLAS/FLL_BA/',
        'forest resources and conservation': '/UGRD/colleges-schools/UGAGL/FRC_BSF/',
        'french and francophone studies': '/UGRD/colleges-schools/UGLAS/FFR_BA/',
        'geography': '/UGRD/colleges-schools/UGLAS/GPY_BA_BS/',
        'geology': '/UGRD/colleges-schools/UGLAS/GLY_BA_BS/',
        'geomatics': '/UGRD/colleges-schools/UGAGL/GEM_BSGE/',
        'german': '/UGRD/colleges-schools/UGLAS/FGR_BA/',
        'graphic design': '/UGRD/colleges-schools/UGART/GRD_BFAG/',
        'health education and behavior': '/UGRD/colleges-schools/UGHHU/HEB_BSHE/',
        'health science': '/UGRD/colleges-schools/UGPBH/HES_BHS/',
        'hebrew': '/UGRD/colleges-schools/UGLAS/FHE_BA/',
        'hispanic and latin american languages, literatures and linguistics': '/UGRD/colleges-schools/UGLAS/HLL_BA/',
        'history': '/UGRD/colleges-schools/UGLAS/HY_BA/',
        'horticultural science': '/UGRD/colleges-schools/UGAGL/HOS_BS/',
        'industrial and systems engineering': '/UGRD/colleges-schools/UGENG/ISE_BSIS/',
        'information systems': '/UGRD/colleges-schools/UGBUS/IST_BSBA/',
        'interdisciplinary studies | clas': '/UGRD/colleges-schools/UGLAS/IDS_BA_BS/',
        'interior design': '/UGRD/colleges-schools/UGDCP/IND_BDES/',
        'international studies': '/UGRD/colleges-schools/UGLAS/INS_BA/',
        'italian': '/UGRD/colleges-schools/UGLAS/FIT_BA/',
        'japanese': '/UGRD/colleges-schools/UGLAS/FJA_BA/',
        'jewish studies': '/UGRD/colleges-schools/UGLAS/JST_BA/',
        'journalism': '/UGRD/colleges-schools/UGJRC/JM_BSJ/',
        'landscape architecture | 4-year professional program': '/UGRD/colleges-schools/UGDCP/LAE_BLAE/',
        'linguistics': '/UGRD/colleges-schools/UGLAS/LIN_BA/',
        'management': '/UGRD/colleges-schools/UGBUS/MGT_BSBA/',
        'marine sciences | cals': '/UGRD/colleges-schools/UGAGL/IS_BS07/',
        'marine sciences | clas': '/UGRD/colleges-schools/UGLAS/IDS_BS17/',
        'marketing': '/UGRD/colleges-schools/UGBUS/MKG_BSBA/',
        'materials science and engineering': '/UGRD/colleges-schools/UGENG/MSE_BSMS/',
        'mathematics': '/UGRD/colleges-schools/UGLAS/MAT_BA_BS/',
        'mechanical engineering': '/UGRD/colleges-schools/UGENG/MCE_BSME/',
        'media production, management, and technology': '/UGRD/colleges-schools/UGJRC/TEL_BSTE/',
        'microbiology and cell science | cals': '/UGRD/colleges-schools/UGAGL/MCB_BS/',
        'microbiology and cell science | clas': '/UGRD/colleges-schools/UGLAS/MCY_BS/',
        'music education': '/UGRD/colleges-schools/UGART/MUE_BMUE/',
        'music | bachelor of arts': '/UGRD/colleges-schools/UGART/MUS_BA/',
        'music | bachelor of music': '/UGRD/colleges-schools/UGART/MUS_BMUS/',
        'natural resource conservation': '/UGRD/colleges-schools/UGAGL/NRC_BSF/',
        'nuclear engineering': '/UGRD/colleges-schools/UGENG/NUE_BSNE/',
        'nursing': '/UGRD/colleges-schools/UGNUR/NSG_BSN/',
        'nutritional sciences': '/UGRD/colleges-schools/UGAGL/NUT_BS/',
        'pharmacy | preprofessional': '/UGRD/academic-programs/UGPHM/PHA_NOD/',
        'philosophy': '/UGRD/colleges-schools/UGLAS/PPY_BA/',
        'physics': '/UGRD/colleges-schools/UGLAS/PS_BA_BS/',
        'plant science': '/UGRD/colleges-schools/UGAGL/PLS_BS/',
        'political science': '/UGRD/colleges-schools/UGLAS/POL_BA/',
        'portuguese': '/UGRD/colleges-schools/UGLAS/HLL_BA01/',
        'psychology': '/UGRD/colleges-schools/UGLAS/PSY_BS_BS01/',
        'public health': '/UGRD/colleges-schools/UGPBH/PBH_BPH/',
        'public relations': '/UGRD/colleges-schools/UGJRC/PR_BSPR/',
        'religion': '/UGRD/colleges-schools/UGLAS/RLN_BA/',
        'russian': '/UGRD/colleges-schools/UGLAS/FRU_BA/',
        'sociology': '/UGRD/colleges-schools/UGLAS/SOC_BA/',
        'soil and water sciences': '/UGRD/colleges-schools/UGAGL/SWS_BS/',
        'spanish': '/UGRD/colleges-schools/UGLAS/HLL_BA02/',
        'spanish and portuguese': '/UGRD/colleges-schools/UGLAS/HLL_BA/HLL_BA03/',
        'sport management': '/UGRD/colleges-schools/UGHHU/SPM_BSSP/',
        'statistics': '/UGRD/colleges-schools/UGLAS/STA_BA_BS/',
        'sustainability and the built environment': '/UGRD/colleges-schools/UGDCP/SUB_BSUB_BSUB01/',
        'sustainability studies': '/UGRD/colleges-schools/UGLAS/SST_BA/',
        'theatre': '/UGRD/colleges-schools/UGART/THE_BA/',
        'theatre performance': '/UGRD/colleges-schools/UGART/THF_BFA/',
        'theatre production': '/UGRD/colleges-schools/UGART/TPR_BFA/',
        'tourism, hospitality and event management': '/UGRD/colleges-schools/UGHHU/TRM_BSTM/',
        'wildlife ecology and conservation': '/UGRD/colleges-schools/UGAGL/WEC_BS/',
        "women's studies": '/UGRD/colleges-schools/UGLAS/WMS_BA/',
        'zoology': '/UGRD/colleges-schools/UGLAS/ZLY_BS/'
    },

    'Minors': {
        'accounting ': '/UGRD/colleges-schools/UGACT/ACT_UMN/',
        'actuarial science ': '/UGRD/colleges-schools/UGLAS/ACS_UMN/',
        'aerospace leadership ': '/UGRD/academic-programs/military-science/aerospace-leadership/',
        'african studies ': '/UGRD/colleges-schools/UGLAS/AFS_UMN/',
        'african-american studies ': '/UGRD/colleges-schools/UGLAS/AFA_UMN/',
        'agricultural and natural resource communication ': '/UGRD/colleges-schools/UGAGL/AGC_UMN/',
        'agricultural and natural resource ethics and policy ': '/UGRD/colleges-schools/UGAGL/AEP_UMN/',
        'agricultural and natural resource law ': '/UGRD/colleges-schools/UGAGL/ANL_UMN/',
        'agricultural curriculum and development ': '/UGRD/colleges-schools/UGAGL/ACD_UMN/',
        'american indian and indigenous studies ': '/UGRD/colleges-schools/UGLAS/AIN_UMN/',
        'anthropology ': '/UGRD/colleges-schools/UGLAS/APY_UMN/',
        'arabic language and literature ': '/UGRD/colleges-schools/UGLAS/ALL_UMN/',
        'art ': '/UGRD/colleges-schools/UGART/STR_UMN/',
        'art history ': '/UGRD/colleges-schools/UGART/ARH_UMN/',
        'art history  | new world school of the arts': '/UGRD/colleges-schools/UGART/ARH_UMN_NWSA/',
        'asian studies ': '/UGRD/colleges-schools/UGLAS/AST_UMN/',
        'asian-american studies ': '/UGRD/colleges-schools/UGLAS/AAS_UMN/',
        'astronomy ': '/UGRD/colleges-schools/UGLAS/ATY_UMN/',
        'bioinformatics ': '/UGRD/colleges-schools/UGAGL/BIF_UMN/',
        'biomechanics ': '/UGRD/colleges-schools/UGENG/BIM_UMN/',
        'biomolecular engineering ': '/UGRD/colleges-schools/UGENG/BMO_UMN/',
        'botany ': '/UGRD/colleges-schools/UGLAS/BOT_UMN/',
        'business administration ': '/UGRD/colleges-schools/UGBUS/BUS_UMN/',
        'chemistry ': '/UGRD/colleges-schools/UGLAS/CHY_UMN/',
        'classical studies ': '/UGRD/colleges-schools/UGLAS/CLC_UMN/',
        'communication sciences and disorders ': '/UGRD/colleges-schools/UGPBH/CSD_UMN/',
        'communication studies ': '/UGRD/colleges-schools/UGLAS/CMS_UMN/',
        'computer and information science and engineering ': '/UGRD/colleges-schools/UGENG/CIE_UMN/',
        'dance ': '/UGRD/colleges-schools/UGART/DAN_UMN/',
        'deaf and hearing sciences  ': '/UGRD/colleges-schools/UGPBH/DHS_UMN/',
        'digital arts and sciences ': '/UGRD/colleges-schools/UGART/DAR_UMN/',
        'disabilities in society ': '/UGRD/colleges-schools/UGEDU/DIS_UMN/',
        'disability science ': '/UGRD/colleges-schools/UGPBH/DSC_UMN/',
        'early childhood studies  ': '/UGRD/colleges-schools/UGEDU/ECS_UMN/',
        'east asian languages and literatures ': '/UGRD/colleges-schools/UGLAS/EAC_EAJ_UMN/',
        'east-central european studies ': '/UGRD/colleges-schools/UGLAS/EEU_UMN/',
        'economics ': '/UGRD/colleges-schools/UGLAS/ECO_UMN/',
        'education studies ': '/UGRD/colleges-schools/UGEDU/EDS_UMN/',
        'educational technology ': '/UGRD/colleges-schools/UGEDU/EDX_UMN/',
        'electrical engineering ': '/UGRD/colleges-schools/UGENG/ELE_UMN/',
        'engineering innovation ': '/UGRD/colleges-schools/UGENG/EIN_UMN/',
        'english ': '/UGRD/colleges-schools/UGLAS/EH_UMN/',
        'entomology and nematology ': '/UGRD/colleges-schools/UGAGL/ENY_UMN/',
        'entrepreneurship ': '/UGRD/colleges-schools/UGBUS/ENT_UMN/',
        'environmental horticulture ': '/UGRD/colleges-schools/UGAGL/EVH_UMN/',
        'environmental justice and policy ': '/UGRD/colleges-schools/UGLAS/EJP_UMN/',
        'environmental science ': '/UGRD/colleges-schools/UGNTR/ENV_UMN/',
        'european union studies ': '/UGRD/colleges-schools/UGLAS/EUS_UMN/',
        'event management ': '/UGRD/colleges-schools/UGHHU/EVM_UMN/',
        'extension education ': '/UGRD/colleges-schools/UGAGL/EXE_UMN/',
        'family, youth and community sciences ': '/UGRD/colleges-schools/UGAGL/FYC_UMN/',
        'fisheries and aquatic sciences ': '/UGRD/colleges-schools/UGAGL/FAS_UMN/',
        'florida teaching ': '/UGRD/colleges-schools/UGEDU/FLT_UMN/',
        'food and resource economics ': '/UGRD/colleges-schools/UGAGL/FRE_UMN/',
        'food science ': '/UGRD/colleges-schools/UGAGL/FOS_UMN/',
        'forest resources and conservation ': '/UGRD/colleges-schools/UGAGL/FRC_UMN/',
        'french and francophone studies ': '/UGRD/colleges-schools/UGLAS/FFS_UMN/',
        'geography ': '/UGRD/colleges-schools/UGLAS/GPY_UMN/',
        'geology ': '/UGRD/colleges-schools/UGLAS/GLY_UMN/',
        'german ': '/UGRD/colleges-schools/UGLAS/GMN_UMN/',
        'golf and sports turf management ': '/UGRD/colleges-schools/UGAGL/GST_UMN/',
        'greek studies ': '/UGRD/colleges-schools/UGLAS/GKS_UMN/',
        'health disparities in society ': '/UGRD/colleges-schools/UGLAS/HDS_UMN/',
        'health promotion ': '/UGRD/colleges-schools/UGHHU/HEP_UMN/',
        'health science ': '/UGRD/colleges-schools/UGPBH/HES_UMN/',
        'hebrew ': '/UGRD/colleges-schools/UGLAS/HBR_UMN/',
        'history ': '/UGRD/colleges-schools/UGLAS/HY_UMN/',
        'horticultural science ': '/UGRD/colleges-schools/UGAGL/HOS_UMN/',
        'information systems ': '/UGRD/colleges-schools/UGBUS/IST_UMN/',
        'innovation ': '/UGRD/colleges-schools/UGLAS/INV_UMN/',
        'international development and humanitarian assistance ': '/UGRD/colleges-schools/UGAGL/IDH_UMN/',
        'international studies in agricultural and life sciences ': '/UGRD/colleges-schools/UGAGL/ISA_UMN/',
        'italian studies ': '/UGRD/colleges-schools/UGLAS/ITA_UMN/',
        'jazz studies ': '/UGRD/colleges-schools/UGART/JZS_UMN/',
        'jewish studies ': '/UGRD/colleges-schools/UGLAS/JST_UMN/',
        'landscape architecture ': '/UGRD/colleges-schools/UGDCP/LAE_UMN/',
        'latin american studies ': '/UGRD/colleges-schools/UGLAS/LAM_UMN/',
        'leadership ': '/UGRD/colleges-schools/UGAGL/LDR_UMN/',
        'linguistics ': '/UGRD/colleges-schools/UGLAS/LIN_UMN/',
        'management and sales in agribusiness ': '/UGRD/colleges-schools/UGAGL/MGT_UMN/',
        'mass communication studies ': '/UGRD/colleges-schools/UGJRC/COM_UMN/',
        'materials science and engineering ': '/UGRD/colleges-schools/UGENG/MSE_UMN/',
        'mathematics ': '/UGRD/colleges-schools/UGLAS/MAT_UMN/',
        'medical geography in global health ': '/UGRD/colleges-schools/UGLAS/MGH_UMN/',
        'medieval and early modern studies ': '/UGRD/colleges-schools/UGLAS/MEM_UMN/',
        'military science and leadership ': '/UGRD/academic-programs/military-science/military-science-leadership/',
        'music history | ethnomusicology ': '/UGRD/colleges-schools/UGART/MHE_UMN/',
        'music performance ': '/UGRD/colleges-schools/UGART/MUP_UMN/',
        'music theory ': '/UGRD/colleges-schools/UGART/MUT_UMN/',
        'nonprofit organizational leadership ': '/UGRD/colleges-schools/UGAGL/NON_UMN/',
        'nuclear and radiological engineering ': '/UGRD/colleges-schools/UGENG/NURE_UMN/',
        'nutritional sciences ': '/UGRD/colleges-schools/UGAGL/NUT_UMN/',
        'organic and sustainable crop production ': '/UGRD/colleges-schools/UGAGL/OSCP_UMN/',
        'packaging science ': '/UGRD/colleges-schools/UGAGL/PKS_UMN/',
        'pathogenesis ': '/UGRD/colleges-schools/UGAGL/PAT_UMN/',
        'philosophy ': '/UGRD/colleges-schools/UGLAS/PPY_UMN/',
        'physics ': '/UGRD/colleges-schools/UGLAS/PS_UMN/',
        'plant molecular and cellular biology ': '/UGRD/colleges-schools/UGAGL/PMB_UMN/',
        'plant science ': '/UGRD/colleges-schools/UGAGL/PLS_UMN/',
        'portuguese ': '/UGRD/colleges-schools/UGLAS/POR_UMN/',
        'precision agriculture ': '/UGRD/colleges-schools/UGAGL/PCA_UMN/',
        'professional selling ': '/UGRD/colleges-schools/UGBUS/SEL_UMN/',
        'public health ': '/UGRD/colleges-schools/UGPBH/PBH_UMN/',
        'public leadership ': '/UGRD/colleges-schools/UGLAS/PBL_UMN/',
        'public relations ': '/UGRD/colleges-schools/UGJRC/PR_UMN/',
        'real estate ': '/UGRD/colleges-schools/UGBUS/REA_UMN/',
        'religion ': '/UGRD/colleges-schools/UGLAS/RLN_UMN/',
        'retailing ': '/UGRD/colleges-schools/UGBUS/RET_UMN/',
        'russian ': '/UGRD/colleges-schools/UGLAS/RUS_UMN/',
        'sales engineering ': '/UGRD/colleges-schools/UGENG/SAE_UMN/',
        'sociology ': '/UGRD/colleges-schools/UGLAS/SOC_UMN/',
        'sociology of social justice and policy ': '/UGRD/colleges-schools/UGLAS/SJP_UMN/',
        'soil and water sciences ': '/UGRD/colleges-schools/UGAGL/SWS_UMN/',
        'spanish ': '/UGRD/colleges-schools/UGLAS/SPN_UMN/',
        'statistics ': '/UGRD/colleges-schools/UGLAS/STA_UMN/',
        'sustainability and the built environment ': '/UGRD/colleges-schools/UGDCP/SUB_UMN/',
        'sustainability studies ': '/UGRD/colleges-schools/UGLAS/SST_UMN/',
        'teaching english as a second language ': '/UGRD/colleges-schools/UGLAS/TSL_UMN/',
        'theatre ': '/UGRD/colleges-schools/UGART/THE_UMN/',
        'theatre production ': '/UGRD/colleges-schools/UGART/TPR_UMN/',
        'theories and politics of sexuality ': '/UGRD/colleges-schools/UGLAS/TPS_UMN/',
        'ufteach | mathematics or science ': '/UGRD/colleges-schools/UGEDU/UF_TEACH/',
        'urban and regional planning ': '/UGRD/colleges-schools/UGDCP/URP_UMN/',
        'wealth management ': '/UGRD/colleges-schools/UGBUS/WMT_UMN/',
        'wildlife ecology and conservation ': '/UGRD/colleges-schools/UGAGL/WEC_UMN/',
        "women's studies ": '/UGRD/colleges-schools/UGLAS/WMS_UMN/',
        'zoology ': '/UGRD/colleges-schools/UGLAS/ZLY_UMN/'
    },

    "Certificates": {
        'advanced engineering ceramics ': '/UGRD/colleges-schools/UGENG/ENG_UCT01/',
        'agroecology and sustainable food systems  ': '/UGRD/colleges-schools/UGAGL/AGL_UCT19/',
        'animal genetics  ': '/UGRD/colleges-schools/UGAGL/AGL_UCT15/',
        'applied theater for health ': '/UGRD/colleges-schools/UGART/ART_UCT08/',
        'art education ': '/UGRD/colleges-schools/UGART/ART_UCT06/',
        'artificial intelligence and data analytics in tourism, hospitality and event management  ': '/UGRD/colleges-schools/UGHHU/HHU_UCT02/',
        'artificial intelligence fundamentals and applications ': '/UGRD/colleges-schools/UGENG/ENG_UCT12/',
        'artificial intelligence in public health and healthcare ': '/UGRD/colleges-schools/UGPBH/PBH_UCT02/',
        'beekeeping ': '/UGRD/colleges-schools/UGAGL/AGL_UCT21/',
        'biomaterials ': '/UGRD/colleges-schools/UGENG/ENG_UCT02/',
        'biosecurity and biological invasions ': '/UGRD/colleges-schools/UGAGL/AGL_UCT14/',
        'cals honor scholar ': '/UGRD/colleges-schools/UGAGL/AGL_UCT01/',
        'ceramics ': '/UGRD/colleges-schools/UGART/ART_UCT02/',
        'challenge 2050 | global leadership and change ': '/UGRD/colleges-schools/UGAGL/AGL_UCT05/',
        'construction management ': '/UGRD/colleges-schools/UGCMN/CMN_UCT04/',
        'creative advertising ': '/UGRD/colleges-schools/UGJRC/JRC_UCT04/',
        'dance in medicine ': '/UGRD/colleges-schools/UGART/ART_UCT03/',
        'data analytics ': '/UGRD/colleges-schools/UGLAS/LAS_UCT23/',
        'east-central european studies ': '/UGRD/colleges-schools/UGLAS/LAS_UCT02/',
        'emergency management ': '/UGRD/colleges-schools/UGCMN/CMN_UCT05/',
        'emergency medical services management ': '/UGRD/colleges-schools/UGCMN/CMN_UCT06/',
        'engineering innovation ': '/UGRD/colleges-schools/UGENG/ENG_UCT09/',
        'engineering leadership ': '/UGRD/colleges-schools/UGENG/ENG_UCT08/',
        'engineering project management  ': '/UGRD/colleges-schools/UGENG/ENG_UCT11/',
        'environmental horticulture management ': '/UGRD/colleges-schools/UGAGL/AGL_UCT02/',
        'environmental policy, law, and regulation ': '/UGRD/colleges-schools/UGAGL/AGL_UCT18/',
        'ethics and society ': '/UGRD/colleges-schools/UGLAS/LAS_UCT22/',
        'european jewish studies ': '/UGRD/colleges-schools/UGLAS/LAS_UCT17/',
        'european union studies ': '/UGRD/colleges-schools/UGLAS/LAS_UCT03/',
        'fire ecology and management ': '/UGRD/colleges-schools/UGAGL/AGL_UCT17/',
        'gateway to agroecology ': '/UGRD/colleges-schools/UGAGL/AGL_UCT13/',
        'geographic artificial intelligence and big data  ': '/UGRD/colleges-schools/UGLAS/LAS_UCT24/',
        'geological sciences ': '/UGRD/colleges-schools/UGLAS/LAS_UCT18/',
        'geomatics ': '/UGRD/colleges-schools/UGAGL/AGL_UCT06/',
        'geospatial information analysis ': '/UGRD/colleges-schools/UGLAS/LAS_UCT04/',
        'graphic design ': '/UGRD/colleges-schools/UGART/ART_UCT07/',
        'holocaust studies ': '/UGRD/colleges-schools/UGLAS/LAS_UCT05/',
        'horticultural therapy ': '/UGRD/colleges-schools/UGAGL/AGL_UCT12/',
        'international communication ': '/UGRD/colleges-schools/UGJRC/JRC_UCT07/',
        'international relations ': '/UGRD/colleges-schools/UGLAS/LAS_UCT06/',
        'landscape pest management ': '/UGRD/colleges-schools/UGAGL/AGL_UCT07/',
        'latin american studies ': '/UGRD/colleges-schools/UGLAS/LAS_UCT08/',
        'legal history ': '/UGRD/colleges-schools/UGLAS/LAS_UCT20/',
        'mapping with small unmanned aerial systems ': '/UGRD/colleges-schools/UGAGL/AGL_UCT11/',
        'media sales ': '/UGRD/colleges-schools/UGJRC/JRC_UCT01/',
        'medical anthropology ': '/UGRD/colleges-schools/UGLAS/LAS_UCT09/',
        'medical entomology ': '/UGRD/colleges-schools/UGAGL/AGL_UCT08/',
        'medical geography ': '/UGRD/colleges-schools/UGLAS/LAS_UCT19/',
        'metallurgical engineering ': '/UGRD/colleges-schools/UGENG/ENG_UCT03/',
        'meteorology and climatology ': '/UGRD/colleges-schools/UGLAS/LAS_UCT10/',
        'music education  ': '/UGRD/colleges-schools/UGART/ART_UCT09/',
        'music in medicine ': '/UGRD/colleges-schools/UGART/ART_UCT04/',
        'music performance ': '/UGRD/colleges-schools/UGART/ART_UCT05/',
        'nuclear radiation and reactor analysis ': '/UGRD/colleges-schools/UGENG/ENG_UCT04/',
        'nuclear thermal systems analysis ': '/UGRD/colleges-schools/UGENG/ENG_UCT05/',
        'packaging engineering ': '/UGRD/colleges-schools/UGENG/ENG_UCT10/',
        'pest control technology ': '/UGRD/colleges-schools/UGAGL/AGL_UCT09/',
        'political campaigning ': '/UGRD/colleges-schools/UGLAS/LAS_UCT11/',
        'polymer science and engineering ': '/UGRD/colleges-schools/UGENG/ENG_UCT06/',
        'public affairs ': '/UGRD/colleges-schools/UGLAS/LAS_UCT12/',
        'recreation resources management ': '/UGRD/colleges-schools/UGAGL/AGL_UCT20/',
        'russian and east-european area studies ': '/UGRD/colleges-schools/UGLAS/LAS_UCT14/',
        'semiconductor materials ': '/UGRD/colleges-schools/UGENG/ENG_UCT07/',
        'senior fire officer ': '/UGRD/colleges-schools/UGCMN/CMN_UCT08/',
        'spanish for the professions ': '/UGRD/colleges-schools/UGLAS/LAS_UCT15/',
        'sport management ': '/UGRD/colleges-schools/UGHHU/HHU_UCT01/',
        'teaching english as a second language ': '/UGRD/colleges-schools/UGLAS/LAS_UCT16/',
        'translation studies ': '/UGRD/colleges-schools/UGLAS/LAS_UCT21/',
        'urban forestry ': '/UGRD/colleges-schools/UGAGL/AGL_UCT16/',
        'urban pest management ': '/UGRD/colleges-schools/UGAGL/AGL_UCT10/',
        'visual arts in medicine ': '/UGRD/colleges-schools/UGART/ART_UCT01/'
    }
}

def GetDB():
    return FullData